{"name": "人脸信息管理--访客等级管理", "status": "skipped", "statusDetails": {"message": "Skipped: 普利人脸服务连接目前不可用", "trace": "('TestCases\\\\Test3_FaceRecognition\\\\test_1_face_info_manage.py', 56, 'Skipped: 普利人脸服务连接目前不可用')"}, "parameters": [{"name": "data", "value": "{'case_id': 2, 'sheet_name': 'set_customer_level', 'title': '正常设置', 'customer': '修改的访客001', 'level': '黑名单'}"}], "start": 1607074566260, "stop": 1607074566260, "uuid": "f6e1d920-ef12-4020-b6b9-b8a29467d998", "historyId": "85b5789f9967dcc8ef52485557f53bbe", "testCaseId": "872c1b06f8a520b632522d11bfbfb59d", "fullName": "TestCases.Test3_FaceRecognition.test_1_face_info_manage.TestFaceRecognition#test_set_customer_level", "labels": [{"name": "feature", "value": "人脸识别"}, {"name": "epic", "value": "项目名称：中控平台V2.1"}, {"name": "story", "value": "人脸信息管理"}, {"name": "tag", "value": "@pytest.mark.skip(reason='普利人脸服务连接目前不可用')"}, {"name": "tag", "value": "@pytest.mark.usefixtures('refresh')"}, {"name": "parentSuite", "value": "TestCases.Test3_FaceRecognition"}, {"name": "suite", "value": "test_1_face_info_manage"}, {"name": "subSuite", "value": "TestFaceRecognition"}, {"name": "host", "value": "DESKTOP-901EL0R"}, {"name": "thread", "value": "9616-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.Test3_FaceRecognition.test_1_face_info_manage"}]}